### PR TITLE
Add Passport/DiscordStrategy

### PR DESCRIPTION
**Pull request by infiniwave**

### CODE REVIEW

**Comment by fracturx** [comment]
Use the passport.use middleware to create a new **DiscordStrategy** with the required creditentials from environment variables. Urls supplied here must be part of the authentication route.

**Comment by fracturx** [comment]
oh nvm im dumb

**Comment by computergeek12** [comment]
Oh, okay.

**Comment by CreeperPlanet26** [comment]
hey @computergeek12 could you please fix your linting issues

**Comment by computergeek12** [comment]
No. If you REALLY like linting, then do it yourself. @CreeperPlanet26

**Pull request merged**
