### PR TITLE
Task #3 

### PR DESCRIPTION
**Pull request by computergeek12**
- Fix "MONGO-URI" in the readme
- I do not know why all the other files are appearing
- Add task #3 in Passport authentication

### CODE REVIEW

**Comment by computergeek12** [comment]
Oops, it's the readme.

**Comment by computergeek12** [comment]
Alright, the extra files problem seems to be fixed.

**Comment by CreeperPlanet26** [comment]
I would use a router instead of /api/auth/discord just / to make it cleaner

**Comment by CreeperPlanet26** [comment]
Could you run `npm run lint:fix`

**Comment by CreeperPlanet26** [comment]
Sorry `npm run lintfix`

**Pull request merged**
