### PR TITLE
Merge pull request #14 from computergeek12/master

### PR DESCRIPTION
**Pull request by computergeek12**

### CODE REVIEW

**Comment by fracturx** [comment]
the guilds field must be an array of object ids (belonging to the guild)

**Comment by fracturx** [comment]
also, it would be helpful to specify an _id field

**Comment by computergeek12** [comment]
I fixed the ObjectId array.

**Comment by fracturx** [comment]
i don't think that's valid syntax, wrap the array brackets around the object for the guild and remove the array brackets around the type: ObjectId

**Comment by fracturx** [comment]
the rest of the guild object is fine

**Comment by computergeek12** [comment]
Alright, done. :D

**Pull request merged**
