### PR TITLE
Re-PR (Strategy)

### PR DESCRIPTION
**Pull request by computergeek12**

### CODE REVIEW

**Comment by computergeek12** [comment]
Oops, need async function.

**Comment by fracturx** [comment]
Also, please do `npm run lint` on your local machine and push that as a commit. Your discord strategy file breaks a lot of eslint rules.

**Comment by computergeek12** [comment]
I have a question. Why does linting matter so much?

**Comment by CreeperPlanet26** [comment]
For the code base to stay consistent. It's good open source practice too.

**Comment by fracturx** [comment]
Linting helps the code stay maintainable as more and more commits pile up. If one person uses spaces and another uses tabs, conflicts will arise. If one person indents too much and another person indents too little, conflicts will arise.

**Comment by fracturx** [comment]
Also make sure to pull from the remote repo.

**Comment by computergeek12** [comment]
Sigh. How can I fix these at once?

Personally, I do not like linting.

**Comment by computergeek12** [comment]
There's like a million errors out there.

**Comment by fracturx** [comment]
a lot of these are really silly, like quotes and semi colons.
fix them easily using the built in vs code extension or just running `npm run lintfix`
You'll have to fix any non auto-fixable errors yourself though

**Comment by computergeek12** [comment]
GOD. On VS Code I installed ESLint and there suddenly was 50 errors.

**Comment by CreeperPlanet26** [comment]
That's why u should run the lint fix command

**Comment by fracturx** [comment]
why'd you close it?

**Pull request closed without merging**
