### PR TITLE
Add prefix by guild ID

### PR DESCRIPTION
**Pull request by infiniwave**

### CODE REVIEW

**Comment by computergeek12** [comment]
Alright, there was a conflict that I resolved.

**Comment by CreeperPlanet26** [comment]
This should be able to work without a req.user because in the bot when we fetch the prefix then it would fail because there is not req.user

**Comment by computergeek12** [comment]
Wait, then how do we make sure that the person on the dashboard has authenticated/has permissions?

**Comment by computergeek12** [comment]
Since in the requirements it says to verify authentication.

**Comment by computergeek12** [comment]
Maybe we can make a special authenticator for the bot?

**Comment by CreeperPlanet26** [comment]
look at Passport Configuration: 2 in the readme it explains your question

**Comment by computergeek12** [comment]
2 - Set up a callback function for initializing the Discord Strategy such that it validates whether or not the authorized user is already in the database. If they are, attempt to update the database with their current discord tag. If they are not in the database, create a new user in the database using the profile parameter passed in the callback. ONLY GUILDS THAT ARE:

MUTUAL BETWEEN THE USER AND THE BOT

HAVE THE MANAGE SERVERS PERMISSIONS (can be found by applying AND bitmask to the raw guild.permissions object from the discord api)

MAY BE PUT IN THE DATABASE

**Comment by computergeek12** [comment]
How does it explain my question?

**Comment by CreeperPlanet26** [comment]
when the user logs in, only the guilds that they have perms to are added to there guilds

**Comment by computergeek12** [comment]
Yes, I know that?

**Comment by CreeperPlanet26** [comment]
so the user would have perms when seeing the prefix

**Comment by CreeperPlanet26** [comment]
thats how we determine

**Comment by computergeek12** [comment]
No, I mean you said to do it without req.user so that the bot can go through. If I did it without req.user then how would I verify the user's authentication?

**Comment by CreeperPlanet26** [comment]
so we dont need the req.user because there would be no way they can access the guild if they dont have perms. because they user.guilds

**Comment by CreeperPlanet26** [comment]
u can check if the user.guilds array includes the guild that they are trying to get

**Comment by computergeek12** [comment]
No, then how would we let the bot through?

**Comment by CreeperPlanet26** [comment]
hmmm

**Comment by computergeek12** [comment]
Maybe the bot uses a special authentication token?

**Comment by CreeperPlanet26** [comment]
i mean rn it doesn't matter if GETTING the prefix is protected. but UPDATING it does matter

**Comment by computergeek12** [comment]
Well, maybe if the bot posted an authentication token of bla bla bla then it would let the bot through, and if there was no token it would check the user authentication?

**Comment by CreeperPlanet26** [comment]
yeah we could do that we could also have a field called 
```js
body {
isBot: boolean
}
```
i dont think this is good tho

**Comment by computergeek12** [comment]
then people would just spoof that

**Comment by computergeek12** [comment]
do some secret token or something

**Comment by computergeek12** [comment]
maybe something like this:
```js
if (req.headers.token && req.headers.token === process.env.AUTH_TOKEN) {
    const { guildId } = req.params;
    const guild = await Guild.findOne({ guildId });
    if (!guild) return res.sendStatus(404);
    res.send({ guildId, prefix: guild.prefix });
  } else {
    req.user = req.session.user;
    if (!req.user) return res.sendStatus(401);
    const { guildId } = req.params;
    const guild = await Guild.findOne({ guildId });
    if (!guild) return res.sendStatus(404);
    if (!req.user.guilds.find(async (i) => {
      const g = await Guild.findById(i);
      if (g.guildId === guildId) return true;
      return false;
    })) return res.sendStatus(404);
    // ^ 404 is in the requirements, HOWEVER we should make
    //   it 401 as it exists but isn't managable by the user.
    res.send({ guildId, prefix: guild.prefix });
  }```

**Comment by fahimmehraj** [comment]
pull from remote please, the actual content of the files shouldn't be that different

**Comment by fahimmehraj** [comment]
also, the bot project should have a separate mongoose connection for itself connecting to the same database directly. headers specific to bots are way out of the scope of this event. every time a message is sent, the bot will fetch the prefix from the database and check if the message is a command. every time a user joins, the bot will fetch the auto role settings from the database. every time a role is given, the bot will check to see if the muted role was given. it's not the most efficient solution, but others such as websockets aren't what this event is all about

**Comment by fahimmehraj** [comment]
The last comment is right, it should send 401 if the guild exists but not in the user's guilds array. I'll try to test in a few hours.

**Comment by infiniwave** [comment]
Hello?

**Comment by sohank1** [comment]
Yeah

**Pull request closed without merging**
